/* SPDX-License-Identifier: BSD-2-Clause
 *
 * Copyright (C) 2022 Renesas Electronics Corp.
 */

#ifndef _RZFIVE_PLATFORM_H_
#define _RZFIVE_PLATFORM_H_

#include "../../andes/ae350/common-platform.h"

enum sbi_ext_andes_fid {
	SBI_EXT_RENESAS_RZFIVE_GET_MCACHE_CTL_STATUS = 0,
	SBI_EXT_RENESAS_RZFIVE_GET_MMISC_CTL_STATUS,
	SBI_EXT_RENESAS_RZFIVE_SET_MCACHE_CTL,
	SBI_EXT_RENESAS_RZFIVE_SET_MMISC_CTL,
	SBI_EXT_RENESAS_RZFIVE_ICACHE_OP,
	SBI_EXT_RENESAS_RZFIVE_DCACHE_OP,
	SBI_EXT_RENESAS_RZFIVE_L1CACHE_I_PREFETCH,
	SBI_EXT_RENESAS_RZFIVE_L1CACHE_D_PREFETCH,
	SBI_EXT_RENESAS_RZFIVE_NON_BLOCKING_LOAD_STORE,
	SBI_EXT_RENESAS_RZFIVE_WRITE_AROUND,
};

#endif /* _RZFIVE_PLATFORM_H_ */
